---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Keepalive

on:
  workflow_call:
    secrets:
      app_id:
        description: "App ID of the application used to generate a token"
        required: true
      app_private_key:
        description: "Private key of the application used to generate a token"
        required: true

jobs:
  keepalive:
    name: Keep scheduled GitHub workflows alive
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Generate GitHub App Token"
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: "${{ secrets.app_id }}"
          private-key: "${{ secrets.app_private_key }}"

      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Keep scheduled GitHub workflows alive
        uses: gautamkrishnar/keepalive-workflow@2a8ae70f39b79fb50659d17ccc6f372f461813b2 # v2.0.10
        with:
          use_api: true
          gh_token: ${{ steps.app-token.outputs.token }}
          committer_username: greyrock-repo-duster[bot]
          committer_email: greyrock-repo-duster <112729691+greyrock-repo-duster[bot]@users.noreply.github.com>
